### ISSUE TITLE
Promote dune to > 2.0

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#106]
Currently, sandmark only works with system dune < 2.0. We use dune.1.11.4 (See https://github.com/ocaml-bench/sandmark/blob/master/README.md#pre-requisites). Using dune > 2.0 will break the builds of some packages. The necessary fix is:

- [ ] Install system dune version > 2.0
- [ ] Start a benchmarking run and fix all the failing package builds. 

Moving forward, this is quite critical as many packages will no longer build with dune < 2.0.

**Comment by shakthimaan** [comment]
The following two PRs:
* Update decompress benchmarks https://github.com/ocaml-bench/sandmark/pull/131
* Update dependency packages to use dune.2.5.1 and Multicore OCaml 4.10.0 https://github.com/ocaml-bench/sandmark/pull/132
Both the serial and parallel benchmarks run fine!

**Comment by kayceesrk** [comment]
#131 and #132 have been merged.
