### ISSUE TITLE
Additional benchmarks - hamming and soli

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark#119]
There are some benchmarks which are not in sandmark but are used by others:
 - hamming.ml: exists in ocaml testsuite, js_of_ocaml benchmarks and operf-micro:
    https://github.com/ocaml/ocaml/blob/4.10/testsuite/tests/misc/hamming.ml
 - soli.ml: exists in ocaml testsuite and js_of_ocaml benchmarks:
    https://github.com/ocaml/ocaml/blob/4.10/testsuite/tests/misc-unsafe/soli.ml

**Comment by ernestmusong** [comment]
Hello @Sudha247 I would like to work on this Issue.

**Comment by Sudha247** [comment]
Hi @ernestmusong! Sure, you can pickup either one of the two benchmarks listed above to begin with.

This section details the procedure to add a new benchmark to sandmark: https://github.com/ocaml-bench/sandmark#adding-benchmarks. Feel free to post here if you have any questions.

**Comment by ernestmusong** [comment]
> Hi @ernestmusong! Sure, you can pickup either one of the two benchmarks listed above to begin with.
> 
> This section details the procedure to add a new benchmark to sandmark: https://github.com/ocaml-bench/sandmark#adding-benchmarks. Feel free to post here if you have any questions.

Thanks @Sudha247

**Comment by ernestmusong** [comment]
> > Hi @ernestmusong! Sure, you can pickup either one of the two benchmarks listed above to begin with.
> > This section details the procedure to add a new benchmark to sandmark: https://github.com/ocaml-bench/sandmark#adding-benchmarks. Feel free to post here if you have any questions.
> 
> Thanks @Sudha247

Working on it.

**Comment by ernestmusong** [comment]
Hello @Sudha247 I've created a new folder in benchmarks and added the hamming.ml file to it but i see that this folder must have it's own dune file which i don't know how to add. Can i use an existing folder with a dune file to add this hamming.ml file to it?

**Comment by ernestmusong** [comment]
Hi @Sudha247 I've created a pull request for this issue, what's next?
Can I find another issue to work on while waiting for your response on the PR?
