### ISSUE TITLE
Measurements of code size

### ISSUE THREAD

**Issue by mshinwell** [ocaml-bench/sandmark#122]
For compiler benchmarking it's important to have measurements of code size.  The size of the text section of the executable should be fine.

**Comment by mshinwell** [comment]
As I just mentioned on slack, we shouldn't measure the text section size: instead sum the sizes of all text symbols whose names match `caml[A-Z].*` plus those matching `caml_{apply,curry,tuplify}.*`.  This will exclude the runtime in particular.

**Comment by shakthimaan** [comment]
The `codesize` attribute has been added in the PR https://github.com/ocaml-bench/sandmark/pull/165. Please feel free to re-open if you face any issues or create a new one if you have additional requirements. Thanks!
