### ISSUE TITLE
BUILD_ONLY needs to exit with error if package installation fails 

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark#145]
At present, the BUILD_ONLY environment variable stops before executing the benchmarks. We need a way to exit with an error status if any of the dependency installation packages fail. We use `--best-effort` to ignore any build errors and proceed.

In particular, `frama-c` (https://github.com/ocaml-bench/sandmark/issues/17) needs to be built successfully for this change to be useful with the CI.

**Comment by kayceesrk** [comment]
#147 fixes this problem in a different way. Rather than attempting to fix `frama-c`, #147 takes the easier route of running a subset of benchmarks in the CI.
