### ISSUE TITLE
Are we able to make ctypes automatically work for both multicore and stock ocaml

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark#15]
Right now we have a workaround for getting ctypes to work on multicore:
 https://github.com/ocamllabs/sandmark#ctypes

Is there a solution that will make it work on both stock ocaml and multicore without editing the source location?

**Comment by shakthimaan** [comment]
Yes. ctypes.0.15.0 builds fine now with 4.12.0+ for both +stock and +multicore. Hence, closing this issue.
