### ISSUE TITLE
alt-ergo benchmarks fail on multicore due to Obj.truncate usage

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark#16]
The alt-ergo benchmarks do not run on multicore, for example:
```
Fatal error: exception Failure("Obj.truncate not supported")
        orun benchmarks/alt-ergo/alt-ergo-yyll.bench
```
The problem is that Obj.truncate is not supported on multicore. 

For info, Obj.truncate will be deprecated in OCaml (likely 4.09): 
  https://github.com/ocaml/ocaml/pull/2279

**Comment by shakthimaan** [comment]
The use of `prefix`, and `libdir` to `configure` helps build alt-ergo with Sandmark, along with its benchmarks. 
https://github.com/ocaml-bench/sandmark/pull/160
