### ISSUE TITLE
[RFC] Classifying benchmarks based on running time

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#179]
Currently, we have classified benchmarks using two tags -- `macro_bench` and `runs_in_ci`. This is a useful classification, but we've had cases of mislabelling where benchmarks that run for a few milliseconds being classified as macro. Moreover, the original idea of `runs_in_ci` was meant to be running those benchmarks run reasonably fast so that we don't exhaust the 1hr CI limit. But it is unclear whether this is being followed necessarily. There are a few benchmarks that now run for more than 100 seconds, but don't bring in much value themselves. They tend to be too long to be useful for an initial benchmarking of a new feature.

![image](https://user-images.githubusercontent.com/410484/94886225-0e7ff280-0490-11eb-8e94-e0e587d5d775.png)

To address this I propose the following scheme. We will get rid of `macro_bench` and `runs_in_ci` and instead use the following classification:

* `lt_1s` - benchmarks that run for less than 1 second
* `1s_10s` - benchmarks that run for at least 1 second but less than 10 seconds
* `10s_100s` - benchmarks that run for at least 10 seconds but less than 100 seconds
* `gt_100s` - benchmarks that run for at least 100 seconds

We classify the benchmarks based on their running time on the `turing` machine: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz. 

For the initial performance benchmarking, all the benchmarks in the 1s to 100s range should be considered. This will be the replacement for `macro_bench`. 

For the CI, we will run benchmarks that are in the 1s to 10s range. This will be the replacement for `runs_in_ci` tag. 

Any parallel benchmark should have a serial baseline version that runs for at least 10s. Otherwise, the parallelization overheads outweigh the benefit of parallelism. 

We should have a hard look at any benchmarks that run for less than 1s and see whether they're giving us any useful signals.

**Comment by ctk21** [comment]
Having things classified such that people can select what they run classified by runtime is reasonable, often for the initial run you just want to look at a collection of the macro benchmarks. 

We have had success at pin-pointing issues with some of the micro-benchmarks (e.g. C call overhead, cost of local roots in the hash function, read-barrier overheads, stack switching costs), so I wouldn't argue that they are without use. However they are probably only useful when you want to look at something specific where a micro-benchmark makes sense. 

If we classify by runtime, then it is possible to have a script which can automatically tag them into the runtime buckets.

**Comment by kayceesrk** [comment]
> We have had success at pin-pointing issues with some of the micro-benchmarks (e.g. C call overhead, cost of local roots in the hash function, read-barrier overheads, stack switching costs), so I wouldn't argue that they are without use. 

That makes sense. It would be useful to associate with the microbenchmarks what they're meant to be measuring in comments.

> If we classify by runtime, then it is possible to have a script which can automatically tag them into the runtime buckets.

Yes, but I suspect that since we need to do this just once, manually tagging them might be faster. :-)

**Comment by shakthimaan** [comment]
Can we add a couple of more tags for this classification on the running time?
* Hours: The sample benchmark tests for`Coq` run for few hours, and it will be good to see how the the code performs over time.
* Days: Database performance benchmarks with varying loads are run for at least 24-48 hours, to see their behavior. Since, these systems are meant to be run without downtime, it will be good collect data for such longer periods, and see how the system behaves. `Irmin` benchmarks could possibly be added.

**Comment by singhalshubh** [comment]
Lets close this issue. Its resolved in https://github.com/ocaml-bench/sandmark/pull/188

**Comment by kayceesrk** [comment]
Thanks @singhalshubh.
