### ISSUE TITLE
Rename (or remove?) lu_decomposition benchmark in numerical-analysis

### ISSUE THREAD

**Issue by sadiqj** [ocaml-bench/sandmark#182]
We have `LU_decomposition` in `multicore-numerical` which can be a source of confusion.

If the `numerical-analysis` implementation doesn't differ significantly from the one in `multicore-numerical` then we should just remove it - otherwise we should rename it.

**Comment by ctk21** [comment]
The implementations are different. Maybe a rename is easiest? 
Say `numerical-analysis/lu_decomposition.ml` -> `numerical_analysis/crout_decomposition.ml`

**Comment by ctk21** [comment]
Fixed by #183
