### ISSUE TITLE
Reimplement broken pausetimes support

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#218]
In Multicore OCaml 4.12.0, the catapult format (used by `chrome://tracing/`) based event tracing is deprecated. Multicore 4.12.0 will soon produce CTF based traces https://github.com/ocaml-multicore/ocaml-multicore/pull/527. We need to update the scripts to adapt to the new tracing framework. This involves several tasks:

1. Modify the pausetimes scripts for [multicore](https://github.com/ocaml-bench/sandmark/blob/master/pausetimes/pausetimes_multicore) and [stock](https://github.com/ocaml-bench/sandmark/blob/master/pausetimes/pausetimes_trunk) to emit the CTF based traces
2. Rewrite the [tail latency computation scripts](https://github.com/ocaml-bench/sandmark/blob/master/pausetimes/process_eventlog.py) to read the CTF format directly. Catapult traces produced by Multicore OCaml quickly go to Gigabytes in size and it wasn't practical to analyse the pausetime for long-running programs due to the large file sizes. 
3. Possibly, the new tail latency scripts should be implemented in OCaml rather than python. We observed that python happens to be really slow in processing medium-sized eventlog traces; multiple minutes for processing the eventlog of a single program run. If it turns out to be slow to process the CTF traces, we should consider rewriting this in OCaml for speed.

**Comment by Engil** [comment]
This should be rather simple to reimplement in OCaml:
https://github.com/ocaml-multicore/eventlog-tools
The Multicore branch contains the latest version compatible with our trace format.
This would involve writing a script like the chrome converter here: https://github.com/ocaml-multicore/eventlog-tools/blob/multicore/bin/eventlog_to_chrome.ml

**Comment by shubhamkumar13** [comment]
#233 resolves the issue, this can now be closed
