### ISSUE TITLE
View results for a set of benchmarks in the nightly notebooks

### ISSUE THREAD

**Issue by Sudha247** [ocaml-bench/sandmark#231]
(This is in the context of benchmark nightly runs on a remote machine)

It will be nice to have a way to select a set of benchmarks and view only results of those benchmarks. It will be useful to select them based on:
* Individual benchmarks
* Bench tags

**Comment by shubhamkumar13** [comment]
This issue has been resolved in the current `sandmark-nightly`.
For eg. if I select 2 timestamps
![sandmark#231](https://user-images.githubusercontent.com/13629677/124296974-31067f80-db78-11eb-85c6-973b3eed58ff.png)

Then I can only view those 2 while selecting the baseline
![sandmark#231_2](https://user-images.githubusercontent.com/13629677/124297035-411e5f00-db78-11eb-8e51-d24b4648f58b.png)

**Comment by shubhamkumar13** [comment]
@Sudha247 issue moved to [sandmark-nightly#8](https://github.com/ocaml-bench/sandmark-nightly/issues/8).

**Comment by Sudha247** [comment]
Sure, thanks for moving this to sandmark-nightly.
