### ISSUE TITLE
Implement pausetimes support in sandmark_nightly

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#236]
See pause times results in the [ICFP 20 paper](https://arxiv.org/pdf/2004.11663.pdf) (sequential and parallel pausetimes in Fig 10 and 12, respectively) for what the graphs should look like. 

Dependent on #218.

**Comment by shubhamkumar13** [comment]
Pausetimes for 4.12 is now a part of the sandmark nightly run

**Comment by kayceesrk** [comment]
I don't think the resolution message is quite right. Are you saying that pausetimes only works on sandmark nightly, but not if you run it by hand. Can you also add the PR which fixes this for context?

**Comment by shubhamkumar13** [comment]
I think I did something wrong where I didn't create a PR and pushed directly to master, I'll make sure this is something I don't repeat so I do apologise for that.
I can list down some of the commits that made these changes
- [changes made to the notebook](https://github.com/ocaml-bench/sandmark-nightly/commit/7cc9d4fd79697c9d71a24b615cebf9ad6a21c420)
- the following commits were shell script improvements and other minor merge commits
  - https://github.com/ocaml-bench/sandmark-nightly/commit/6a548ea91818e2db64195e51b4f84ad6c69f0d9c
  - https://github.com/ocaml-bench/sandmark-nightly/commit/8a67860a18e1c911062cdd34e25981c199431b1d
  - https://github.com/ocaml-bench/sandmark-nightly/commit/64bc404a8b02340eab4ba99d48c095acc90cdb97
  - https://github.com/ocaml-bench/sandmark-nightly/commit/8cce0a672dd04d4e56b19b4f3926fc73a468a27f

Again I'm sorry for making this messier than it should be for me and others referring this issue

**Comment by shubhamkumar13** [comment]
> Are you saying that pausetimes only works on sandmark nightly

I meant in addition to sandmark (after [sandmark#233] (https://github.com/ocaml-bench/sandmark/pull/233)) it is now also a part of the sandmark-nightly notebooks
