### ISSUE TITLE
Run sandmark_nightly on a larger machine

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#237]
Currently, sandmark nightly results are gathered on a tuned machine at IITM which is an Intel Xeon Gold 5120 CPU with 2-sockets, 28-cores out of which 24 cores have been isolated for performance benchmarking. Some of the [recent improvements](https://github.com/ocaml-multicore/domainslib/pull/29) to `Domainslib` only make observable differences at much larger core counts. Sandmark nightly should be run on a machine with large core counts (~64+). 

These results should be collected under separate `sequential` and `parallel` directories. One idea for the directory structure organisation would be `sandmark_nightly/results/<machine_name>/sequential` and `sandmark_nightly/results/<machine_name>/parallel`. The interactive notebook may correspondingly be updated such that they present a drop-down box with the machine names first, which then loads the corresponding benchmark runs.

What is `navajo` being used for @shakthimaan?

**Comment by kayceesrk** [comment]
We should use `navajo`. We seem to have a previous issue to track this: https://github.com/ocaml-bench/sandmark/issues/95. Luckily the dependent issues seem to be resolved.

**Comment by shubhamkumar13** [comment]
Sandmark nightly is now running on navajo. This issue can be closed.

**Comment by kayceesrk** [comment]
Can you link to the PR or Issue on Sandmark nightly for posterity?

**Comment by shubhamkumar13** [comment]
This issue doesn't have a PR for the same reason as #236 

Although the commits which add sandmark nightly to navajo are the following :
- https://github.com/ocaml-bench/sandmark-nightly/commit/d9dd7ff27249bc212a467f63b4a099efb27cf43c
- https://github.com/ocaml-bench/sandmark-nightly/commit/8789c2ffe2308c90c9c4ba192b9fc8c707cfbd3f
- https://github.com/ocaml-bench/sandmark-nightly/commit/8d8b31381d0062ee74d01c84f3c960123c067ec0
- https://github.com/ocaml-bench/sandmark-nightly/commit/55401a65faefa2df594debf868de280f6cb37573
