### ISSUE TITLE
Move `sandmark_nightly` to ocaml-bench org

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#238]
Currently the repo is under @shubhamkumar13's personal account. Please transfer the repo to `ocaml-bench` org.

**Comment by shubhamkumar13** [comment]
`sandmark-nightly` is now in `ocaml-bench` org and the previous repository has been archived with an updated readme pointing to [ocaml-bench/sandmark-nightly](https://github.com/ocaml-bench/sandmark-nightly).

Closing this.
