### ISSUE TITLE
Add irmin tree benchmark

### ISSUE THREAD

**Issue by Sudha247** [ocaml-bench/sandmark#243]
It will be useful to add [Irmin tree benchmark](https://github.com/mirage/irmin/blob/master/bench/irmin-pack/tree.ml) to sandmark. This would require adding any missing dependencies and data files if required.

cc @shubhamkumar13

**Comment by shakthimaan** [comment]
Closing this issue in favor of https://github.com/ocaml-bench/sandmark/issues/299.
