### ISSUE TITLE
tracking dependencies that fail with 4.14.0+trunk

### ISSUE THREAD

**Issue by shubhamkumar13** [ocaml-bench/sandmark#250]
The following dependencies fail to build with `4.14.0+trunk`  + `dune.2.9.0` with the sandmark ci.
This table contains a list of the packages and their respective issues

| Dependency | Github Issue |
|---|---|
| astring  | https://github.com/dbuenzli/astring/issues/20 |
| fmt | https://github.com/dbuenzli/fmt/issues/49 |
| mtime | https://github.com/dbuenzli/mtime/issues/37 |
| ocaml-migrate-parsetree | https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/117 |
| react | https://github.com/dbuenzli/react/issues/34 |
| rresult | https://github.com/dbuenzli/rresult/issues/24 |

To make sure https://github.com/ocaml-bench/sandmark/issues/247 is fixed with https://github.com/ocaml-bench/sandmark/pull/249 the failing benchmarks are removed temporarily.

**Comment by dbuenzli** [comment]
I don't have the time to investigate this but I suspect something is wrong with the upstream install of `compiler-libs.toplevel` or they changed the installation/packaging scheme.

**Comment by dbuenzli** [comment]
It seems the reason was that `Toploop.use_file` was inadvertently nuked. A fix is being proposed upsteam https://github.com/ocaml/ocaml/pull/10557

**Comment by shubhamkumar13** [comment]
This issue can be closed because all the dependencies related 4.14.0+trunk has been resolved and the PR related to 4.14/0+trunk has been merged in https://github.com/ocaml-bench/sandmark/pull/251
