### ISSUE TITLE
instrumented pausetimes for ocaml - 5.00.0+trunk and 4.14.0+domains

### ISSUE THREAD

**Issue by shubhamkumar13** [ocaml-bench/sandmark#266]
Currently sandmark is updated to the latest trunk and multicore variant (#261).

But the instrumented pausetimes for `5.00.0+trunk` and `4.14.0+domains` require trunk to be frozen to update the pausetimes variant in sandmark.

**Comment by kayceesrk** [comment]
The instrumented pause times will have to be redone using eventring.
