### ISSUE TITLE
Move from drone CI to github actions

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#275]
Github actions is better integrated with Github, and all of our other projects are already using Github actions. We should move to it.

**Comment by Abdulrahim2567** [comment]
Hello @Sudha247  @kayceesrk , I'd like to work on this issue. any  headstarts? thanks.

**Comment by shakthimaan** [comment]
The Drone CI file is at https://github.com/ocaml-bench/sandmark/blob/main/.drone.yml. We will need these steps moved to GitHub Actions. Thanks!

**Comment by Sudha247** [comment]
Adding to what @shakthimaan said, the `drone.yml` file has multiple runs, you can pick up one of the jobs first and try to translate that to GitHub Actions, like the `5.0.0+trunk+serial` job for instance: https://github.com/ocaml-bench/sandmark/blob/main/.drone.yml#L55-L79.

This is a useful guide to get started with GitHub Actions: https://docs.github.com/en/actions/quickstart

**Comment by Abdulrahim2567** [comment]
Thank you very much @Sudha247. Working on it.

**Comment by Abdulrahim2567** [comment]
Hello @Sudha247  @shakthimaan  I have submitted a pull request on the main branch (ocaml-bench/sandmark) moving ocaml-5.0.0+trunks+serial from Drone CI to GitHub Actions. please have a look at it. Thanks :)
