### ISSUE TITLE
sandmark.ocamllabs.io shows error instead of parallel benchmarks

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml-bench/sandmark#281]
Visiting https://sandmark.ocamllabs.io/ and clicking “Parallel benchmarks” show a Python KeyError.

**Comment by OlivierNicole** [comment]
As of now this error no longer appears.

**Comment by OlivierNicole** [comment]
I am unable to view parallel benchmarks again due to an interface error @shakthimaan.

![image](https://user-images.githubusercontent.com/14031333/200286322-bb87a47e-badc-4b94-bfab-ed0aba51863a.png)

**Comment by punchagan** [comment]
@OlivierNicole apologies for the inconvenience and thanks for the report!

This should now be [fixed](https://sandmark.tarides.com/?app=Parallel+Benchmarks&parallel_01=20221104&parallel_num_variants=1&parallel_find_by=variant&parallel_02=navajo_5.1.0%2Btrunk%2Bparallel_20221104_9d5c55c&parallel_00=5.1.0%2Btrunk%2Bparallel)

**Comment by OlivierNicole** [comment]
Indeed, thank you!
