### ISSUE TITLE
Update orun --cpu-list other than 1

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark#288]
The `orun` `--cpu-list` is specificed as 1, but, `isolcpus` start from 2- onwards, and hence the same need to be updated.
https://github.com/ocaml-bench/sandmark/blob/main/run_config.json#L5

**Comment by kayceesrk** [comment]
It is useful to add that this is on `turing`, a specific machine that we currently run our benchmarks on.

**Comment by shakthimaan** [comment]
Fixed in https://github.com/ocaml-bench/sandmark/pull/289.
