### ISSUE TITLE
LU_decomposition_multicore.exe 4 2048 loops forever

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark#294]
The `LU_decomposition_multicore.exe 4 2048` runs on a single CPU core instead of four CPU cores and loops forever. This occurs after this merge commit https://github.com/ocaml-bench/sandmark/commit/f3fc54cc9d58b53c5a9adabc1cc6944738a3876d, and the process gets killed. Why so?
![LU-decomposition-multicore-4-2048-single-core](https://user-images.githubusercontent.com/312622/155313974-8e3c5e8f-79bf-4894-8140-37070457ae23.png)

**Comment by kayceesrk** [comment]
You have asked a question. It may be better to CC folks you are directing the question so that they are notified. Not everyone is monitoring the repo. Do you have someone in mind?

**Comment by shakthimaan** [comment]
Yes. @Sudha247 can you please have a look at the change? Thanks!

**Comment by Sudha247** [comment]
#296 has a proposed fix. I'll see how we can make domainslib handle this better.
