### ISSUE TITLE
Remove `failure:ignore` from drone.yml

### ISSUE THREAD

**Issue by Sudha247** [ocaml-bench/sandmark#311]
Ignore failure was added to temporarily ignore build failures on `5.0.0+trunk`. It can be removed now to make CI report failures. (cf. https://github.com/ocaml-bench/sandmark/blob/main/.drone.yml#L65).

**Comment by ritikBhandari** [comment]
Hi,
I have opened a PR for this issue. Plz consider it :)

**Comment by Sudha247** [comment]
Hi @ritikBhandari, thanks for your contribution! I'll take a look at the PR. I know this was a small change, but next time please comment on the issue when you start working on an issue so that others will not be working on the same. :)

**Comment by ritikBhandari** [comment]
I'm sorry. Will keep this in mind.
Thank you!

**Comment by Sudha247** [comment]
fixed by #312
