### ISSUE TITLE
Add nqueens benchmark

### ISSUE THREAD

**Issue by Sudha247** [ocaml-bench/sandmark#322]
Add nqueens benchmark from #173 to the set of parallel benchmarks. #173 already has the necessary changes, only item left to add is a config for the benchmark in [multicore_parallel_navajo_run_config.json](https://github.com/ocaml-bench/sandmark/blob/master/multicore_parallel_navajo_run_config.json)

**Comment by moazzammoriani** [comment]
I suppose I can take this up

**Comment by Sudha247** [comment]
Sure, you can go ahead and work on this. :)

**Comment by Sudha247** [comment]
fixed by #329.
