### ISSUE TITLE
Update mergesort with a faster implementation

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#356]
A simpler version of mergesort is available here: https://github.com/kayceesrk/ocaml5-tutorial/pull/4. Consider replacing the existing mergesort implementation with this.

**Comment by moazzammoriani** [comment]
I was discussing this @Sudha247 just yesterday. In fact, I was only just about to start working on an implementation of mergesort before I saw this. Your existing version will be quite useful.
