### ISSUE TITLE
Revive instrumented pausetimes using eventring

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#358]
OCaml 5 has support for eventring: https://github.com/ocaml/ocaml/blob/trunk/otherlibs/runtime_events/runtime_events.mli, a new ring-buffer based runtime tracing capability. This replaces the earlier eventlog support. The instrumented pausetimes in Sandmark used to be built on the eventlog support. This support has to be rebuilt using eventring.

Given that eventring has a nice OCaml API, it is possible that `orun` may be modified to directly produce the tail latency distribution without having to go through the python post-processing.

**Comment by ElectreAAS** [comment]
My proposal for this is to move from using `orun` to using `olly`, which does substantially the same thing, only with the more modern `Runtime_events` from Stdlib 5.0.
I made a PR linked above to add a json printing option to olly, so it can be easily consumed by sandmark.
The consumption happens in what used to be bash scripts in sandmark, in #390.

**Comment by kayceesrk** [comment]
Thanks @ElectreAAS. I agree with the observersation. In fact, I added the `latency` subcommand to olly for exactly this purpose. Thanks for moving this forward.

**Comment by ElectreAAS** [comment]
I have so far modified the bash script `pausetimes/pausetimes_multicore`, which seems to do the job, but there is another bash script (`pausetimes_trunk`) in the same directory that uses the outdated eventlog. Should I modify this one too?

**Comment by kayceesrk** [comment]
This issue and #362 seem similar. It may be better to close one of them so that the discussion is not split between the two.

**Comment by kayceesrk** [comment]
Is there an issue for tracking the development of UI / jupyter notebook for the instrument pausetimes? 

FYI the latency metrics should not / need not use the instrumented runtime now. The default runtime itself produces the runtime events in the ring buffer. Please ensure that the builds are not using instrumented pausetimes.

**Comment by Firobe** [comment]
> Is there an issue for tracking the development of UI / jupyter notebook for the instrument pausetimes?
> 
I just created an issue for it https://github.com/ocaml-bench/sandmark/issues/420

> FYI the latency metrics should not / need not use the instrumented runtime now. The default runtime itself produces the runtime events in the ring buffer. Olly consumes this buffer to produce latency graphs. Please ensure that the builds are not using instrumented pausetimes.

OK!

**Comment by shakthimaan** [comment]
> Is there an issue for tracking the development of UI 

Do you need the latency graphs to be displayed on a separate page in the Sandmark Nightly service?

**Comment by kayceesrk** [comment]
> Do you need the latency graphs to be displayed on a separate page in the Sandmark Nightly service?

I don't mind if this is a separate page or is on the same page as the `sequential` and `parallel` benchmarks.
