### ISSUE TITLE
Make benchmark wrapper user configurable

### ISSUE THREAD

**Issue by snimmagadda** [ocaml-bench/sandmark#37]
From Tom Kelly on slack: "one thing that would be awesome in sandmark is the ability to configure the benchmark wrapper that collects the stats. Right now we have `orun -o <output> -- <program-to-run> <program-arguments>` which is static in the dune file. It would be nice if we could have the user configure in a central place `<command> -o <output> -- <program-to-run> <program-arguments>`. This can be powerful as you can then get off the shelf wrappers in there like `ocperf.py` and `strace`. It should also allow the user to define the arguments they want to pass to perf. For example they could record all the benchmarks for a given target."

**Comment by ctk21** [comment]
We have this capability with the `wrappers` parameter in `run_config.json`
