### ISSUE TITLE
Add MaPLe benchmarks to Sandmark

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark#401]
A number of benchmarks from the MaPLe available at:

  https://github.com/MPLLang/parallel-ml-bench/tree/main/ocaml
  
The benchmarks are also mentioned in the papers by Sam Westrick at:

  https://www.cs.cmu.edu/~swestric/

It will be useful to create an OCaml version of the same for inclusion in Sandmark.

**Comment by shwestrick** [comment]
Would be great to see these in sandmark! The `tokens`, `primes`, `msort_ints`, and `msort_strings` benchmarks are all new. I may add some more benchmarks in the future, too.

The OCaml source at https://github.com/MPLLang/parallel-ml-bench/tree/main/ocaml should be good to go straight out of the box with OCaml 5 and domainslib 0.4.2. The [accompanying library](https://github.com/MPLLang/parallel-ml-bench/tree/main/ocaml/lib) could also be of independent interest...

If anyone has any questions about the benchmarks, let me know. I'm happy to help!
