### ISSUE TITLE
graph500 failing

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark#406]
@OlivierNicole The `graph500` benchmark is failing on navajo server with the following error message:
```
(cd _build/5.1.0+stable_1/benchmarks/graph500seq && ./gen.exe -scale 21 -edgefactor 16 edges.data)
Generating edge list...
Generated. Time: 96.748229 s.
Fatal error: exception Sys_error("No space left on device")
```

**Comment by OlivierNicole** [comment]
“No space left on device” is a bit strange, as I do not expect the generated file to be bigger than 1 GB. But maybe that is too much, in which case the `-scale` parameter can be lowered down a few notches (output size should be halved at each decrement).
