### ISSUE TITLE
Remote access to Turing broken

### ISSUE THREAD

**Issue by punchagan** [ocaml-bench/sandmark#473]
Unable to remotely login to Turing is causing issues - I made some fixes in #472 that need to be deployed to Turing to restore builds on the machine. We've reached out to the lab admins in IITM, but access hasn't been restored, yet. 

@shakthimaan do you have suggestions on how to bump this up?

**Comment by tmcgilchrist** [comment]
@punchagan @shakthimaan Is this still a problem with getting access to Turing?

**Comment by punchagan** [comment]
> @punchagan @shakthimaan Is this still a problem with getting access to Turing?

Looks like the the remote access is now restored. I'll deploy the changes in #472 and hopefully the builds should succeed soon. Thanks for the ping.

**Comment by punchagan** [comment]
The nightly runs are now running successfully on turing again. Apologies for the inconvenience during the downtime!

**Comment by punchagan** [comment]
Remote access seems to be broken again, and internet access to the machine too.
