### ISSUE TITLE
split out multibench target into serial and parallel

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark#58]
We have old code to split the multibench target into serial and parallel:
https://github.com/ocaml-bench/sandmark/tree/split_multibench_serial_parallel

This issue is a placeholder as we closed out #39 to progress #54

**Comment by kayceesrk** [comment]
Given that #54 is merged, what needs to be added in the `run_config.json` file to be able to run multicore serial and multicore parallel programs?

**Comment by kayceesrk** [comment]
This can be closed now that #68 is merged.
