### ISSUE TITLE
Ability to collect perf stats on a benchmark run

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark#7]
On Linux we would like to be able to collect 'perf stat' on the benchmark process.

We would like to collect the following counters:
  - basic: 
task-clock, instructions, cpu-cycles, stalled-cycles-frontend, branches, branch-misses
 - front-end to back-end pipeline: 
idq_uops_not_delivered.core, lsd.cycles_active
 - memory: 
L1-icache-load-misses, L1-dcache-load-misses, iTLB-load-misses, dTLB-load-misses

**Comment by gretay-js** [comment]
I have a little utility that parses perf stat outputs and prints out a comparison table. 
https://github.com/gretay-js/perfstatdiff/tree/multifile

**Comment by kayceesrk** [comment]
This has been integrated into sandmark. Closing.
