### ISSUE TITLE
Sandmark Analyze notebooks

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark#96]
The new sandmark analyze (https://github.com/ocaml-bench/sandmark-analyze) notebooks should be hosted as a service. This will help the exploration of measurements other than running time.

**Comment by kayceesrk** [comment]
As a first step, we should move the notebooks that we currently have for the parallel programs to this repo.

**Comment by kayceesrk** [comment]
@shakthimaan can I assign this task to you since you are already looking at this issue?

**Comment by shakthimaan** [comment]
JupyterHub is a multi-user server for hosting Jupyter notebooks. `The Littlest Jupyter Hub` installation is capable of hosting 0-100 users. The following steps are used for the installation on Ubuntu 18.04.3 LTS:

```
$ sudo apt install python3 python3-dev git curl
$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin adminuser
```
If you would like to run the the service on a specific port, say "8082", you need to update the same in `/opt/tljh/state/traefix.toml` file. 

By default, the hub login opens at `hostname:15001/hub/login`, which is used by the admin user to create user accounts. The users will be able to login using `hostname:8082/user/username/tree`.

Source: https://tljh.jupyter.org/en/latest/install/custom-server.html

**Comment by kayceesrk** [comment]
Ok. Would you be able to set this up on one of our machines? Also, we should still do https://github.com/ocaml-bench/sandmark/issues/96#issuecomment-609813351

**Comment by kayceesrk** [comment]
> Ok. Would you be able to set this up on one of our machines? Also, we should still do [#96 (comment)](https://github.com/ocaml-bench/sandmark/issues/96#issuecomment-609813351)

I've pushed the notebooks: https://github.com/ocaml-bench/sandmark/tree/master/notebooks

**Comment by shakthimaan** [comment]
The following PR (https://github.com/ocaml-bench/sandmark/pull/109) has been created to:
* Add UI support to interactively select the number of comparisons, bench files and a base variant for the sequential notebook.
* Execute the notebook in JupyterHub CLI using papermill using the following:
```
$ papermill sequential-interactive.ipynb sequential-interactive-output.ipynb -f parameters.yaml
```

**Comment by kayceesrk** [comment]
Would be great to have this documented in README

**Comment by shakthimaan** [comment]
The README has been updated with JupyterHub information and I have added more content with a bit of re-organization. PR at https://github.com/ocaml-bench/sandmark/pull/118

**Comment by kayceesrk** [comment]
We can consider this issue to be closed. Thanks @shakthimaan!
